### ISSUE TITLE
Web-Server Crash after applying php translation file

### ISSUE THREAD

**Issue by Githopp192** [filerun/translations#1]
fileRun software version is 2021.06.27

Download / enable a language like german.php or or dutch.php either via gui or ftp download to system/data/translations

will fully scratch the web-server. No login from anyone is possible anymore.

Full Restore of web-appliance is necessary.

**Comment by filerun** [comment]
Please download the latest version of the translation files from the official FileRun translation tool (https://docs.filerun.com/translating_filerun).
